name: Update GitHub Recent Activity

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual trigger
  push:
    branches:
      - main

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Update recent activity
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT || github.token }}
          username: gobeecode
          limit: 10
          include: commits,pullRequests,issues,discussions
